// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StingrayFeeder.Data;

#nullable disable

namespace stingray_feeder_app.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027223400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StingrayFeeder.Data.Models.Caretaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Caretakers");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.FeedBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BatchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FishId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("UnitWeightGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FishId");

                    b.ToTable("FeedBatches");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.FeedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaretakerId")
                        .HasColumnType("int");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeedBatchId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StingrayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaretakerId");

                    b.HasIndex("FeedBatchId");

                    b.HasIndex("StingrayId");

                    b.ToTable("FeedEvents");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TypicalSizeGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.Stingray", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stingrays");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.FeedBatch", b =>
                {
                    b.HasOne("StingrayFeeder.Data.Models.Fish", "Fish")
                        .WithMany("Batches")
                        .HasForeignKey("FishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fish");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.FeedEvent", b =>
                {
                    b.HasOne("StingrayFeeder.Data.Models.Caretaker", "Caretaker")
                        .WithMany("FeedEvents")
                        .HasForeignKey("CaretakerId");

                    b.HasOne("StingrayFeeder.Data.Models.FeedBatch", "FeedBatch")
                        .WithMany("FeedEvents")
                        .HasForeignKey("FeedBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StingrayFeeder.Data.Models.Stingray", "Stingray")
                        .WithMany("FeedEvents")
                        .HasForeignKey("StingrayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caretaker");

                    b.Navigation("FeedBatch");

                    b.Navigation("Stingray");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.Caretaker", b =>
                {
                    b.Navigation("FeedEvents");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.FeedBatch", b =>
                {
                    b.Navigation("FeedEvents");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.Fish", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("StingrayFeeder.Data.Models.Stingray", b =>
                {
                    b.Navigation("FeedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
